package com.cendrb.cenaonwheels;

import com.cendrb.cenaonwheels.eventhandlers.EntityStruckByLightningHandler;
import com.cendrb.cenaonwheels.eventhandlers.WorldLoadHandler;
import com.cendrb.cenaonwheels.init.*;
import com.cendrb.cenaonwheels.network.SpawnParticleMessage;
import com.cendrb.cenaonwheels.network.SyncEntityNBTMessage;
import com.cendrb.cenaonwheels.proxy.CommonProxy;
import com.sun.corba.se.impl.orbutil.concurrent.Sync;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;

/**
 * Created by cendr_000 on 02.10.2016.
 */
@Mod(modid = RefStrings.MODID, name = RefStrings.NAME, version = RefStrings.VERSION)
public class Core {

    public static SimpleNetworkWrapper networkWrapper;

    @SidedProxy(clientSide = RefStrings.CLIENT_PROXY, serverSide = RefStrings.SERVER_PROXY, modId = RefStrings.MODID)
    public static CommonProxy proxy;

    @Mod.Instance
    public static Core instance = new Core();

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        ModCreativeTabs.init();
        ModItems.init();
        ModBlocks.init();
        ModTileEntities.init();
        ModEntities.init();
        ModRecipes.init();
        ModKlidInfusionRecipes.init();

        proxy.registerEntityRederers();

        networkWrapper = NetworkRegistry.INSTANCE.newSimpleChannel(RefStrings.MODID + "_channel");
        networkWrapper.registerMessage(SpawnParticleMessage.Handler.class, SpawnParticleMessage.class, 0, Side.CLIENT);
        networkWrapper.registerMessage(SyncEntityNBTMessage.Handler.class, SyncEntityNBTMessage.class, 1, Side.CLIENT);

        // set mod info screen from code
        e.getModMetadata().autogenerated = false;
        e.getModMetadata().credits = TextFormatting.BLUE + "Cendrb";
        e.getModMetadata().authorList.add(TextFormatting.RED + "Cendrb");
        e.getModMetadata().description = TextFormatting.YELLOW + "Hehou lukas, ar ju pripert tu goink aut?";
        e.getModMetadata().url = "https://github.com/Cendrb/CenaOnWheels";
        //e.getModMetadata().logoFile = "assets/ultramegafactory/textures/logo/logo.png";
        e.getModMetadata().version = RefStrings.VERSION;
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent e) {
        System.out.println("INIT for " + RefStrings.NAME);

        GameRegistry.registerWorldGenerator(new OreGenerator(), 0);

        // crafting recipes, new handlers
        MinecraftForge.EVENT_BUS.register(new WorldLoadHandler());
        MinecraftForge.EVENT_BUS.register(new EntityStruckByLightningHandler());
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent e) {
        System.out.println("POSTINIT for " + RefStrings.NAME);
        // communicate with other mods
    }
}
