package com.cendrb.cenaonwheels;

import com.cendrb.cenaonwheels.init.ModBlocks;
import com.cendrb.cenaonwheels.init.ModCreativeTabs;
import com.cendrb.cenaonwheels.init.ModItems;
import com.cendrb.cenaonwheels.proxy.CommonProxy;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

/**
 * Created by cendr_000 on 02.10.2016.
 */
@Mod(modid = RefStrings.MODID, name = RefStrings.NAME, version = RefStrings.VERSION)
public class Core {

    @SidedProxy(clientSide = RefStrings.CLIENT_PROXY, serverSide = RefStrings.SERVER_PROXY, modId = RefStrings.MODID)
    public static CommonProxy proxy;

    @Mod.Instance
    public static Core instance = new Core();

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        ModCreativeTabs.init();
        ModItems.init();
        ModBlocks.init();

        // set mod info screen from code
        e.getModMetadata().autogenerated = false;
        e.getModMetadata().credits = TextFormatting.BLUE + "Cendrb";
        e.getModMetadata().authorList.add(TextFormatting.RED + "Cendrb");
        e.getModMetadata().description = TextFormatting.YELLOW + "Hehou lukas, ar ju pripert tu goink aut?";
        e.getModMetadata().url = "https://github.com/Cendrb/CenaOnWheels";
        //e.getModMetadata().logoFile = "assets/ultramegafactory/textures/logo/logo.png";
        e.getModMetadata().version = RefStrings.VERSION;
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent e) {
        System.out.println("INIT for " + RefStrings.NAME);
        // crafting recipes, new handlers
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent e) {
        System.out.println("POSTINIT for " + RefStrings.NAME);
        // communicate with other mods
    }
}
